name: scipy-2021

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pygraphviz
  - pip
  - pip:
    - git+https://github.com/ploomber/ploomber
    - pandas
    - scikit-learn
    - sklearn-evaluation
    - jupyterlab
